version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  prisma
    commands:
      - npx prisma generate production
  compile:
    commands:
      - npx tsc
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .
