version: 0.2

phases:
  install:
    commands:
      - npm install --force
  pre_build:
    commands:
      - npx prisma generate production
  build:
    commands:
      - npx tsc

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .
